env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  import/resolver:
    typescript: {}
rules:
  quotes: ['error', 'double']
  arrow-body-style: ['error', 'always']
  comma-dangle: ['error', 'never']
  prefer-template: 'off'
  import/extensions: [
    'error',
    'ignorePackages',
    {
      'js': 'never',
      'jsx': 'never',
      'ts': 'never',
      'tsx': 'never',
    }
  ]
  react/jsx-filename-extension: ['error', {'extensions': ['.jsx', '.tsx']}]
  react/jsx-uses-react: 'off'
  react/react-in-jsx-scope: 'off'


